# Generated by Django 5.2.7 on 2025-10-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuentrovirtual',
            name='enlace_meet',
        ),
        migrations.RemoveField(
            model_name='encuentrovirtual',
            name='notas_encuentro',
        ),
        migrations.RemoveField(
            model_name='encuentrovirtual',
            name='solicitud',
        ),
        migrations.AlterField(
            model_name='encuentrovirtual',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('completado', 'Completado')], default='programado', max_length=20),
        ),
    ]
