# Generated by Django 5.2.8 on 2025-11-17 19:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0002_remove_encuentrovirtual_enlace_meet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionEncuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad_atencion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentarios', models.TextField(blank=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('encuentro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='encuentros.encuentrovirtual')),
            ],
            options={
                'verbose_name': 'Evaluación de Encuentro',
                'verbose_name_plural': 'Evaluaciones de Encuentros',
            },
        ),
        migrations.CreateModel(
            name='NotaEncuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('privada', models.BooleanField(default=True)),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='encuentros.encuentrovirtual')),
                ('trabajador_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuentros.trabajadorsocial')),
            ],
            options={
                'verbose_name': 'Nota de Encuentro',
                'verbose_name_plural': 'Notas de Encuentros',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RecursoTerapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('video', 'Video'), ('ejercicio', 'Ejercicio'), ('enlace', 'Enlace externo')], max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('encuentros', models.ManyToManyField(blank=True, related_name='recursos', to='encuentros.encuentrovirtual')),
            ],
            options={
                'verbose_name': 'Recurso Terapéutico',
                'verbose_name_plural': 'Recursos Terapéuticos',
            },
        ),
    ]
