# Generated by Django 5.2.8 on 2025-11-17 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0003_evaluacionencuentro_notaencuentro_recursoterapeutico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajadorsocial',
            options={'verbose_name': 'Trabajador Social', 'verbose_name_plural': 'Trabajadores Sociales'},
        ),
    ]
