# Generated by Django 5.2.8 on 2025-11-17 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0004_alter_trabajadorsocial_options'),
        ('solicitudes', '0005_solicitudayuda_acepta_terminos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentrovirtual',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuentros', to='solicitudes.solicitudayuda'),
        ),
        migrations.AlterField(
            model_name='encuentrovirtual',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20),
        ),
    ]
