# Generated by Django 5.2.7 on 2025-10-13 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.categoriaproblema')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('urgencia', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('crisis', 'Crisis Urgente')], max_length=20)),
                ('descripcion_problema', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('evaluando', 'En Evaluación'), ('derivado', 'Derivado a Encuentro'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('categoria_problema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitudes.categoriaproblema')),
                ('sintomas_seleccionados', models.ManyToManyField(to='solicitudes.sintoma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
