# Generated by Django 5.2.7 on 2025-10-13 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudayuda',
            name='categoria_problema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitudes.categoriaproblema'),
        ),
        migrations.AlterField(
            model_name='solicitudayuda',
            name='sintomas_seleccionados',
            field=models.ManyToManyField(blank=True, to='solicitudes.sintoma'),
        ),
        migrations.AlterField(
            model_name='solicitudayuda',
            name='urgencia',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('crisis', 'Crisis Urgente')], default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudayuda',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
