# Generated by Django 5.2.7 on 2025-10-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicitudayuda_categoria_problema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudayuda',
            name='entidad_remision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='informacion_adicional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='max_sesiones',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='remitido_otra_entidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='requiere_ayuda_basica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='sesiones_completadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solicitudayuda',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('evaluando', 'En evaluación'), ('atencion_inmediata', 'Atención Inmediata'), ('programado', 'Encuentro programado'), ('completado', 'Completado'), ('remitido', 'Remitido a otra entidad')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudayuda',
            name='urgencia',
            field=models.CharField(choices=[('baja', 'Baja - Agendar'), ('media', 'Media'), ('alta', 'Alta'), ('crisis', 'Crisis - Intervención Inmediata')], default='media', max_length=20),
        ),
    ]
