# Generated by Django 5.2.7 on 2025-10-13 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_solicitudayuda_entidad_remision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproblema',
            options={'verbose_name': 'Categoría de Problema', 'verbose_name_plural': 'Categorías de Problemas'},
        ),
        migrations.AlterModelOptions(
            name='sintoma',
            options={'verbose_name': 'Síntoma', 'verbose_name_plural': 'Síntomas'},
        ),
        migrations.AlterModelOptions(
            name='solicitudayuda',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Solicitud de Ayuda', 'verbose_name_plural': 'Solicitudes de Ayuda'},
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula de ciudadanía'),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='celular',
            field=models.CharField(default='0000000000', max_length=15, verbose_name='Número de celular'),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='correo_electronico',
            field=models.EmailField(default='temp@example.com', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='descripcion_discapacidad',
            field=models.TextField(blank=True, null=True, verbose_name='Describa su discapacidad (si aplica)'),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de residencia'),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='discapacidad',
            field=models.CharField(choices=[('ninguna', 'No tengo discapacidad'), ('fisica', 'Discapacidad física'), ('visual', 'Discapacidad visual'), ('auditiva', 'Discapacidad auditiva'), ('intelectual', 'Discapacidad intelectual'), ('psicosocial', 'Discapacidad psicosocial'), ('multiple', 'Discapacidad múltiple'), ('otra', 'Otra discapacidad')], default='ninguna', max_length=20, verbose_name='Discapacidad'),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='edad',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], max_length=20, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='grupo_raizal',
            field=models.CharField(choices=[('ninguno', 'No pertenezco a ningún grupo raizal'), ('indigena', 'Indígena'), ('afrodescendiente', 'Afrodescendiente'), ('raizal', 'Raizal'), ('palenquero', 'Palenquero'), ('gitano', 'Gitano/Rom'), ('otro', 'Otro grupo étnico')], default='ninguno', max_length=20, verbose_name='Pertenencia a grupo raizal o étnico'),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='solicitudayuda',
            name='descripcion_problema',
            field=models.TextField(verbose_name='Descripción del problema'),
        ),
        migrations.AlterField(
            model_name='solicitudayuda',
            name='informacion_adicional',
            field=models.TextField(blank=True, null=True, verbose_name='Información adicional'),
        ),
        migrations.AlterField(
            model_name='solicitudayuda',
            name='requiere_ayuda_basica',
            field=models.BooleanField(default=False, verbose_name='Requiere ayuda básica'),
        ),
    ]
