# Generated by Django 5.2.8 on 2025-11-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_alter_categoriaproblema_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudayuda',
            name='acepta_terminos',
            field=models.BooleanField(default=False, verbose_name='Acepta términos y condiciones'),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='acepta_tratamiento_datos',
            field=models.BooleanField(default=False, verbose_name='Acepta tratamiento de datos personales'),
        ),
    ]
